services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    build: 
      context: ./server
      dockerfile: server.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - db
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: client.dev
    ports:
      - "5174:5174"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  mysql_data:
